#ifndef CORE_LIBS_PRX_LIBSCEUSERSERVICE_USERSERVICE_HPP
#define CORE_LIBS_PRX_LIBSCEUSERSERVICE_USERSERVICE_HPP

#include <cstdint>

constexpr int USER_SERVICE_OK = 0;
constexpr int USER_SERVICE_ERROR_INVALID_ARGUMENT = static_cast<int>(0x80960005);
constexpr int USER_SERVICE_ERROR_BUFFER_TOO_SHORT = static_cast<int>(0x8096000A);
constexpr int USER_SERVICE_ERROR_NO_EVENT = -2137653241;
constexpr int USER_SERVICE_USER_ID_INVALID = -1;
constexpr int USER_SERVICE_INITIAL_USER_ID = 0x10000000;
constexpr std::uint32_t USER_SERVICE_EVENT_TYPE_LOGIN = 0;
constexpr const char* USER_SERVICE_INITIAL_USER_NAME = "Player";

#endif
